//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViagemSeg
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Local { get; set; }
        public string elefone { get; set; }
        public string Contato { get; set; }
        public string aspnetusers_Id { get; set; }
    
        public virtual aspnetusers aspnetusers { get; set; }
    }
}
